procedure panta01
@ 07,01 clear to 23,78
@08,02 say 'Titulo         :'
@14,02 say 'Fecha Matric   :'
@15,02 say 'Fecha Tit.     :'
@16,02 say 'Fecha Habil.   :'
@17,02 say  'Fecha Pago    :'
@18,02 say 'Ult.a¤o Pago   :'
@19,02 say 'Venc.Habilitac.:'
@20,02 say 'Fecha Certif   :'
@21,02 say 'Cod.Inscrip.   :'
@16,35 say 'Inicio:'
@17,35 say 'Actual:'
@18,35 say 'A¤o   :'
@19,35 say 'Vencim:'
@13,42 say 'Resol.92/04'
@13,56 say 'Inactividad'

return
