procedure pruecer1
* programa para prueba de impresion de certificados
set console off
set printer on
set device to printer
?
?
?
?
?
?
?
?
?
?
?
?
?'             ALVAREZ,JUAN CARLOS            '
?'             MAESTRO MAYOR DE OBRAS         '
?'             ENET N§ 5 ALVAREZ CONDARCO     '
?
?'               MARTINEZ DE ROSAS 2655       '
?'                             VIVIENDA UNIFAMILIAR PROYECTO'
?' CALCULO, DIRECCION TECNICA, INTALACION ELECTRICA       '
?' PROYECTO DE OBRAS SANITARIAS                           '
?' PROYECTO DE INSTALACION ELECTRICA                      '
?'            VIVIENDA UNIFAMILIAR                        '
?'                       BOULOGNE SUR MER  3455 CIUDAD    '
?
?'            JUAN ALBERTO PUGA                           '
?'                                  DNI 23444555          '
?
?'               SAN MARTIN 1044 1.PISO CIUDAD MENDOZA    '
?
?
?'                   320                         '
?'                     2                          '
?'                           INSTALACION          '
?'______________________________________________________________________'
?
set device to screen
set console on
set printer off