procedure pruecer
* programa para prueba de impresion de certificados
set console off
set printer on
set device to printer
?
?
?
?
?
?
?
?
?
?
?
?'Profesional:________________________________'
?'T¡tulo:_____________________________________'
?'Expedido por:_______________________________'
?
?'Domicilio real:_____________________________'
?'Labor Profesional contratada:___________________________'
?'________________________________________________________'
?'________________________________________________________'
?'________________________________________________________'
?'de la obra:_____________________________________________'
?'Ubicaci¢n del inmueble:_________________________________'
?
?'Comitente:______________________________________________'
?'Documento de Identidad(tipo y n.):______________________'
?
?'Domicilio real:_________________________________________'
?
?
?'Superf. cubierta:_______________________________'
?'Cantidad de Plantas:____________________________'
?'Instalaci¢n complementaria:_____________________'
?'______________________________________________________________________'
?
set device to screen
set console on
set printer off